### ISSUE TITLE
vendor/plugins deprecated in Rails 3.2

### ISSUE THREAD

**Issue by aspiers** [technicalpickles/wheres-your-database-yml-dude#1]
I just upgraded to Rails 3.2 and now I get:

```
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins!
Support for these plugins will be removed in Rails 4.0. Move them out
and bundle them in your Gemfile, or fold them in to your app as
lib/myplugin/* and config/initializers/myplugin.rb. See the release
notes for more on this:
http://weblog.rubyonrails.org/2012/01/04/rails-3-2-0-rc2-has-been-released.
```

**Comment by technicalpickles** [comment]
Best path for this is probably to just convert to a proper gem.

**Comment by aspiers** [comment]
Agreed!

**Comment by abra-chan** [comment]
I get this error even though my vendor/plugins is empty. I only use gems, so I don't understand.

**Comment by abra-chan** [comment]
I should note, however, that I only get the error in production (Heroku Cedar), but not in development. Perhaps they're slipping a plugin into my app on the fly...?

**Comment by abra-chan** [comment]
Yep. That's exactly what's happening. I'll be quiet now. ^_^

-----> Rails plugin injection
       Injecting rails_log_stdout
       Injecting rails3_serve_static_assets

**Comment by technicalpickles** [comment]
Never got to this, so calling this effectively unmaintained 😓
