### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by varunagrawal** [technicalpickles/wheres-your-database-yml-dude#2]
As per the README, I am to use `script/plugin` to install this plugin.

However, I am on Rails 4.2 and `script/plugin` does not exist and `rails plugin install` does not work. Can you please update the README to reflect the correct way to install this plugin?

**Comment by technicalpickles** [comment]
This was reported in https://github.com/technicalpickles/wheres-your-database-yml-dude/issues/1 . It'd need to be a gem to be usable with modern Rails.

I haven't used this personally in many years, so I'm considering this unmaintained. I updated the readme to indicate that.

If you are looking for similar solutions to the problem of keeping usernames and password in database.yaml, I'd consider taking an environment variable based approach. https://devcenter.heroku.com/articles/rails-database-connection-behavior talks about this a bit in detail.
